# -*- coding: utf-8 -*-
"""Анализ резюме.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Duw-EATdWzmyYEiwAAeM0FiRC3dObnja
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.naive_bayes import MultinomialNB
from sklearn.multiclass import OneVsRestClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score
from pandas.plotting import scatter_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

"""# 1. Анализ резюме

## предварителньый анализ
"""

resumeDataSet = pd.read_pickle("/content/drive/MyDrive/Учеба Вышка/Альфа/Диплом/Копия Данные резюме.pkl")
resumeDataSet = resumeDataSet.iloc[:, 1:]
resumeDataSet.head()

print(f"Количество резюме: {len(resumeDataSet)}")
print(f"Количество признаков: {len(resumeDataSet.columns)}")
print(f"Индексы: от {resumeDataSet.index[0]} до {resumeDataSet.index[-1]}")

print("\nСтолбцы:")
for i, col in enumerate(resumeDataSet.columns, 1):
    print(f"{i:2}. {col}")

if 'skills' in resumeDataSet.columns:
    # Анализ структуры навыков
    all_skills = []
    skill_lengths = []

    for skills_list in resumeDataSet['skills']:
        if isinstance(skills_list, list):
            skill_lengths.append(len(skills_list))
            all_skills.extend(skills_list)

    print(f"Всего уникальных навыков: {len(set(all_skills))}")
    print(f"Общее количество упоминаний навыков: {len(all_skills)}")
    print(f"Среднее количество навыков на резюме: {np.mean(skill_lengths):.1f}")
    print(f"Мин/Макс навыков в резюме: {min(skill_lengths)}/{max(skill_lengths)}")

    # Топ-20 навыков
    from collections import Counter
    skill_counter = Counter(all_skills)
    top_skills = skill_counter.most_common(20)

    print("\nТоп-20 самых частых навыков:")
    for skill, count in top_skills:
        print(f"  {skill}: {count} ({count/len(resumeDataSet)*100:.1f}%)")

    # Визуализация
    plt.figure(figsize=(12, 6))
    skills_df = pd.DataFrame(top_skills, columns=['skill', 'count'])
    skills_df.plot(kind='bar', x='skill', y='count', legend=False)
    plt.title('Топ-20 навыков в резюме')
    plt.xlabel('Навык')
    plt.ylabel('Количество упоминаний')
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()

resumeDataSet.shape

resumeDataSet['desired_wage'] = resumeDataSet['desired_wage'].apply(lambda x: x * 91 if x < 10000 else x)
mean_wage = round(resumeDataSet['desired_wage'].mean(), 2)
resumeDataSet['desired_wage'] = resumeDataSet['desired_wage'].apply(lambda x: mean_wage if x == 0 else x)

import nltk
nltk.download('stopwords')
nltk.download('punkt')

!pip install pymorphy2
# !pip install -q pymorphy2==0.9.1

import nltk
from nltk.corpus import stopwords
import string
from wordcloud import WordCloud
import pymorphy2

oneSetOfStopWords = set(stopwords.words('russian')+['``',"''", '—'])
# lemmatizer = pymorphy2.MorphAnalyzer()

try:
    lemmatizer = pymorphy2.MorphAnalyzer()
except Exception as e:
    # Создаем простой заглушечный объект
    class SimpleLemmatizer:
        def parse(self, word):
            class ParseResult:
                def __init__(self, word):
                    self.normal_form = word.lower()
            return [ParseResult(word)]
    lemmatizer = SimpleLemmatizer()

totalWords =[]
Sentences = resumeDataSet['skills'].values
cleanedSentences = ""
for records in Sentences:
  for i in records:
    if i.lower().find('английский') == -1 and i.lower().find('english') == -1 and i.lower().find('русский') == -1 and i.lower().find('russian') == -1 and i.lower().find('французский') == -1 and i.lower().find('армянский') and i.lower().find('казахский') and i.lower().find('немецкий') and i.lower().find('украинский') and i.lower().find('узбекский') and i.lower().find('испанский') and i.lower().find('french') and i.lower().find('spanish') and i.lower().find('японский') and i.lower().find('азербайджанский') and i.lower().find('uzbek') and i.lower().find('турецкий') and i.lower().find('german') and i.lower().find('b1') and i.lower().find('начальный') and i.lower().find('родной') and i.lower().find('native') and i.lower().find('родной') and i.lower().find('с1') and i.lower().find('с2') and i.lower().find('b1') and i.lower().find('b1') and i.lower().find('b2') and i.lower().find('a2') and i.lower().find('начальный') and i.lower().find('таджикский') and i.lower().find('kazakh'):
      spis = []
      for word in i.split():
        if len(word) != 1 and word not in string.punctuation and word not in oneSetOfStopWords and word != '2012' and word != '2016' and word != '2003' and word != '2008' and word != '3d' and word != '3ds' and word != '4d' and word != '4hana' and word != '11' and word != '14' and word != '17':
            word = word.replace('1с', '1c')
            word = lemmatizer.parse(word)
            word = word[0].normal_form
            spis.append(word)
      totalWords.append(' '.join(spis).lower())
      cleanedSentences += ' '.join(spis).lower() + ' '
    else:
      continue
wordfreqdist = nltk.FreqDist(totalWords)
mostcommon = wordfreqdist.most_common(500)
print(mostcommon)
print(cleanedSentences)

"""Визуализация топ n слов"""

from nltk.corpus import stopwords
stop_words = stopwords.words('russian')
wc = WordCloud(stopwords=stop_words).generate(cleanedSentences)
plt.figure(figsize=(10,10))
plt.imshow(wc, interpolation='bilinear')
plt.axis("off")
plt.show()

"""Собираем отдельно в список топ 100 навыков"""

all_skills = []
for i in mostcommon[:300]:
  if i[0] == '':
    continue
  all_skills.append(i[0])

"""1.Векторизация слов с помощью модели TF-IDF

Выбор рандомных 500 резюме
"""

random_rows = resumeDataSet.sample(500)
df = random_rows['skills']
df

df = resumeDataSet['skills']
df

"""Подготовка данных: удаление лишних слов, лематизация слов из навыков резюме"""

oneSetOfStopWords = set(stopwords.words('russian')+['``',"''", '—'])
wages = resumeDataSet['desired_wage'].tolist()

try:
    lemmatizer = pymorphy2.MorphAnalyzer()
except Exception as e:
    # Создаем простой заглушечный объект
    class SimpleLemmatizer:
        def parse(self, word):
            class ParseResult:
                def __init__(self, word):
                    self.normal_form = word.lower()
            return [ParseResult(word)]
    lemmatizer = SimpleLemmatizer()

# lemmatizer = pymorphy2.MorphAnalyzer()
total = []
new_wages = []
k = 0
for records in df:
  totalWords =[]
  cleanedSentences = ""
  for i in records:
    if i.lower().find('английский') == -1 and i.lower().find('english') == -1 and i.lower().find('русский') == -1 and i.lower().find('russian') == -1 and i.lower().find('французский') == -1 and i.lower().find('армянский') and i.lower().find('казахский') and i.lower().find('немецкий') and i.lower().find('украинский') and i.lower().find('узбекский') and i.lower().find('испанский') and i.lower().find('french') and i.lower().find('spanish') and i.lower().find('японский') and i.lower().find('азербайджанский') and i.lower().find('uzbek') and i.lower().find('турецкий') and i.lower().find('german') and i.lower().find('b1') and i.lower().find('начальный') and i.lower().find('родной') and i.lower().find('native') and i.lower().find('родной') and i.lower().find('с1') and i.lower().find('с2') and i.lower().find('b1') and i.lower().find('b1') and i.lower().find('b2') and i.lower().find('a2') and i.lower().find('начальный') and i.lower().find('таджикский') and i.lower().find('kazakh'):
      spis = []
      for word in i.split():
        if len(word) != 1 and word not in string.punctuation and word not in oneSetOfStopWords and word != '2012' and word != '2016' and word != '2003' and word != '2008' and word != '3d' and word != '3ds' and word != '4d' and word != '4hana' and word != '11' and word != '14' and word != '17':
            word = word.replace('1с', '1c')
            word = lemmatizer.parse(word)
            word = word[0].normal_form
            spis.append(word)
      totalWords.append(' '.join(spis).lower())
    else:
      continue
  totalWords = [element for element in totalWords if element != '']
  if len(totalWords) != 0:
    total.append(totalWords)
    new_wages.append(wages[k])
  k += 1
print(total)

"""Сортировка навыков внутри каждого резюме, отбор навыка только если оно встретилось > 12 раз во всех резюме"""

dict_mostcommon = dict(mostcommon)
total_new = []
wages_res = []
k = 0
for resumes in total:
  resumes = [(resume, dict_mostcommon[resume]) for resume in resumes if resume in dict_mostcommon.keys() and dict_mostcommon[resume] > 12]
  resumes = sorted(resumes, key=lambda x: x[1], reverse=True)
  resumes = [skill for skill, _ in resumes]
  #resumes = resumes[:(len(resumes)*3//4)]---Возможно нужно поиграться со значениями
  if len(resumes) != 0:
    total_new.append(resumes)
    wages_res.append(new_wages[k])
  k += 1
#len(total_new)

"""1.Векторизация TF-IDF"""

from sklearn.feature_extraction.text import TfidfVectorizer
preprocessed_texts_single_tokens = []
preprocessed_texts_single_tokens = [
    [phrase.strip().replace(' ', '_') for phrase in text] for text in total_new
]

resume_texts = [' '.join(text).strip() for text in preprocessed_texts_single_tokens]

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(resume_texts)
feature_names = vectorizer.get_feature_names_out()

tfidf_dense = tfidf_matrix.todense()
df_tfidf = pd.DataFrame(tfidf_dense, columns=feature_names)

df_tfidf.head(10)

df_tfidf.shape

"""Мешок слов"""

from sklearn.feature_extraction.text import CountVectorizer
preprocessed_texts_single_tokens = []
preprocessed_texts_single_tokens = [
    [phrase.strip().replace(' ', '_') for phrase in text] for text in total_new
]

resume_texts = [' '.join(text).strip() for text in preprocessed_texts_single_tokens]

vectorizer = CountVectorizer()
tfidf_matrix = vectorizer.fit_transform(resume_texts)
feature_names = vectorizer.get_feature_names_out()

tfidf_dense = tfidf_matrix.todense()
df_tfidf = pd.DataFrame(tfidf_dense, columns=feature_names)

df_tfidf.head()

"""Метрика Tf"""

from sklearn.feature_extraction.text import CountVectorizer
preprocessed_texts_single_tokens = []
preprocessed_texts_single_tokens = [
    [phrase.strip().replace(' ', '_') for phrase in text] for text in total_new
]

resume_texts = [' '.join(text).strip() for text in preprocessed_texts_single_tokens]

vectorizer = CountVectorizer()
tfidf_matrix = vectorizer.fit_transform(resume_texts)
feature_names = vectorizer.get_feature_names_out()


# Преобразование в TF (относительные частоты)
X_tf = tfidf_matrix.toarray().astype(float)
for i in range(X_tf.shape[0]):
    X_tf[i] /= X_tf[i].sum()

# Создание DataFrame для наглядности
df_tfidf = pd.DataFrame(X_tf, columns=feature_names)
df_tfidf.head(10)

"""## Кластеризация

Кластеризация k-means
"""

from sklearn.cluster import KMeans
from sklearn.preprocessing import normalize
n = 10

tfidf_matrix_transposed = tfidf_matrix.transpose()

# Нормализация данных может улучшить результаты кластеризации
normalized_matrix = normalize(tfidf_matrix_transposed)

# Применение K-means кластеризации к транспонированной и нормализованной матрице
kmeans = KMeans(n_clusters=n, random_state=42)  # Выбор количества кластеров
clusters = kmeans.fit_predict(normalized_matrix)

# Создание DataFrame для анализа результатов кластеризации
skills_df = pd.DataFrame({
    'skill': vectorizer.get_feature_names_out(),
    'cluster': clusters
})

# Анализ кластеров
a = []
for cluster_num in range(n):
    print(f"Кластер {cluster_num}:")
    print(skills_df[skills_df['cluster'] == cluster_num]['skill'].tolist())
    print("\n")
    a.append(skills_df[skills_df['cluster'] == cluster_num]['skill'].tolist())

"""Облако слов"""

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Список слов для облака слов
words = [
  'jupyter', 'jupyter_notebook', 'matplotlib', 'numpy', 'pandas', 'scipy', 'sklearn', 'xgboost', 'алгоритм_структура_данные', 'математический_анализ', 'математический_статистика', 'теория_вероятность']

# Создание строки текста из списка слов
text = " ".join(words)

# Создание объекта WordCloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)

# Визуализация облака слов
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Список слов для облака слов
words = ['dax', 'ms_office', 'ms_power_bi', 'oracle_pl', 'power_bi', 'power_query', 'tableau', 'аналитика', 'визуализация_данные', 'подготовка_презентация', 'статистика']

# Создание строки текста из списка слов
text = " ".join(words)

# Создание объекта WordCloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)

# Визуализация облака слов
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Список слов для облака слов
words = ['computer vision', 'deep learning', 'keras', 'matlab', 'ml', 'pytorch', 'tensorflow']

# Создание строки текста из списка слов
text = " ".join(words)

# Создание объекта WordCloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)

# Визуализация облака слов
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Список слов для облака слов
words = ['cocoapods', 'core_data', 'ios', 'mac_os', 'objective', 'realm', 'rxswift', 'snapkit', 'swift', 'swiftui', 'uikit', 'unit_testing', 'viper', 'xcode']

# Создание строки текста из списка слов
text = " ".join(words)

# Создание объекта WordCloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)

# Визуализация облака слов
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Список слов для облака слов
words = ['cocoapods', 'core_data', 'ios', 'mac_os', 'objective', 'realm', 'rxswift', 'snapkit', 'swift', 'swiftui', 'uikit', 'unit_testing', 'viper', 'xcode']

# Создание строки текста из списка слов
text = " ".join(words)

# Создание объекта WordCloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)

# Визуализация облака слов
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Список слов для облака слов
words = ['ajax', 'angular', 'css', 'html', 'javascript', 'jquery', 'mysql', 'php', 'xml']

# Создание строки текста из списка слов
text = " ".join(words)

# Создание объекта WordCloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)

# Визуализация облака слов
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

from sklearn.cluster import KMeans
from sklearn.preprocessing import normalize
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn.decomposition import TruncatedSVD
# Уменьшение размерности для визуализации
svd = TruncatedSVD(n_components=3)
reduced_data = svd.fit_transform(normalized_matrix)

# Визуализация результатов
plt.figure(figsize=(10, 8))
plt.scatter(reduced_data[:, 0], reduced_data[:, 1], c=clusters, cmap='viridis', marker='o', alpha=0.5)
plt.colorbar()  # Показать цветовую шкалу
plt.title('Визуализация кластеров TF-IDF с использованием TruncatedSVD')
plt.xlabel('Компонента 1')
plt.ylabel('Компонента 2')
plt.show()

from sklearn.decomposition import TruncatedSVD
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans
from sklearn.preprocessing import normalize
import matplotlib.pyplot as plt

n_clusters = 10
svd = TruncatedSVD(n_components=50)  # Выбираем 50 компонент для начального уменьшения
svd_result = svd.fit_transform(normalized_matrix)

# Дополнительное уменьшение размерности с помощью t-SNE
tsne = TSNE(n_components=2, perplexity=30, n_iter=300)
tsne_result = tsne.fit_transform(svd_result)

# Визуализация
plt.figure(figsize=(16, 12))
cmap = plt.get_cmap('nipy_spectral')
colors = cmap(np.linspace(0, 1, n_clusters))
for idx in range(n_clusters):
    points = tsne_result[clusters == idx]
    plt.scatter(points[:, 0], points[:, 1], s=30, c=[colors[idx]], label=f'Cluster {idx+1}')

plt.title('Визуализация 50 кластеров с использованием t-SNE')
plt.xlabel('t-SNE компонента 1')
plt.ylabel('t-SNE компонента 2')
plt.legend(markerscale=2, bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, calinski_harabasz_score
from sklearn.metrics import davies_bouldin_score
from sklearn.preprocessing import normalize

# Нормализация данных и конвертация в плотный формат
normalized_matrix = normalize(tfidf_matrix_transposed).toarray()  # Изменение здесь

# Диапазон количества кластеров для анализа
range_n_clusters = list(range(2, 350))  # Начинаем с 2, так как для 1 кластера Silhouette не определен

# Подготовка списков для хранения метрик
silhouette_avg = []
calinski_harabasz_scores = []
wcss = []
dunn = []
davies_bouldin_scores = []

for n_clusters in range_n_clusters:
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    cluster_labels = kmeans.fit_predict(normalized_matrix)

    # Силуэтный коэффициент
    silhouette_avg.append(silhouette_score(normalized_matrix, cluster_labels))

    # Calinski-Harabasz Index
    calinski_harabasz_scores.append(calinski_harabasz_score(normalized_matrix, cluster_labels))

    # Сумма квадратов внутри кластера
    wcss.append(kmeans.inertia_)

    #Davies_bouldin_score
    davies_bouldin_scores.append(davies_bouldin_score(normalized_matrix, cluster_labels))


# Визуализация результатов
import matplotlib.pyplot as plt

plt.figure(figsize=(18, 5))

plt.subplot(1, 3, 1)
plt.plot(range_n_clusters, silhouette_avg, marker='o')
plt.title('Silhouette Score')
plt.xlabel('Number of clusters')
plt.ylabel('Silhouette Score')

plt.subplot(1, 3, 2)
plt.plot(range_n_clusters, calinski_harabasz_scores, marker='o')
plt.title('Calinski-Harabasz Score')
plt.xlabel('Number of clusters')
plt.ylabel('Calinski-Harabasz Score')

plt.subplot(1, 3, 3)
plt.plot(range_n_clusters, wcss, marker='o')
plt.title('WCSS')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')


plt.tight_layout()
plt.show()

"""## Кластеризация 2

Вариант, не деля словосочетания на слова
"""

resume_texts = [' '.join(resume) for resume in total_new]

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform(resume_texts)
feature_names = vectorizer.get_feature_names_out()

tfidf_dense = tfidf_matrix.todense()
df_tfidf = pd.DataFrame(tfidf_dense, columns=feature_names)

df_tfidf.head()

from sklearn.cluster import KMeans
from sklearn.preprocessing import normalize
n = 53
tfidf_matrix_transposed = tfidf_matrix.transpose()

# Нормализация данных может улучшить результаты кластеризации
normalized_matrix = normalize(tfidf_matrix_transposed)

# Применение K-means кластеризации к транспонированной и нормализованной матрице
kmeans = KMeans(n_clusters=n, random_state=42)  # Выбор количества кластеров
clusters = kmeans.fit_predict(normalized_matrix)

# Создание DataFrame для анализа результатов кластеризации
skills_df = pd.DataFrame({
    'skill': vectorizer.get_feature_names_out(),
    'cluster': clusters
})

# Анализ кластеров
for cluster_num in range(n):
    print(f"Кластер {cluster_num}:")
    print(skills_df[skills_df['cluster'] == cluster_num]['skill'].tolist())
    print("\n")

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Список слов для облака слов
words = [
    'jupyter notebook', 'learn', 'matplotlib', 'numpy', 'pandas', 'plotly', 'scikit', 'scipy', 'seaborn', 'sklearn', 'статистический анализ']

# Создание строки текста из списка слов
text = " ".join(words)

# Создание объекта WordCloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)

# Визуализация облака слов
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Список слов для облака слов
words = ['dax', 'ms_excel', 'ms_office', 'power_bi', 'power_query', 'sas', 'tableau', 'vba', 'аналитика', 'аналитический_исследование', 'аналитический_мышление', 'сбор_анализ_информация']

# Создание строки текста из списка слов
text = " ".join(words)

# Создание объекта WordCloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)

# Визуализация облака слов
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Список слов для облака слов
words = ['computer vision', 'keras', 'matlab', 'ml', 'opencv', 'pytorch', 'tensorflow', 'машинный обучение']

# Создание строки текста из списка слов
text = " ".join(words)

# Создание объекта WordCloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)

# Визуализация облака слов
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

"""Иерархическая кластеризация"""

tfidf_dense_transposed = tfidf_matrix_transposed.todense()
feature_names = vectorizer.get_feature_names_out()
df_tfidf_transposed = pd.DataFrame(tfidf_dense_transposed, index=feature_names)
df_tfidf_transposed

df_tfidf_transposed.to_csv('matrix_for_cluster.csv')

from sklearn.manifold import TSNE

tsne = TSNE(n_components=3, random_state=0)
X_2d = tsne.fit_transform(np.asarray(tfidf_dense_transposed))

plt.figure(figsize=(6, 5))
plt.scatter(X_2d[:, 0], X_2d[:, 1], c=clusters)
plt.colorbar()  # Показать цветовую шкалу меток кластеров
plt.title('t-SNE визуализация кластеров')
plt.show()

from scipy.cluster.hierarchy import dendrogram, linkage
from matplotlib import pyplot as plt

linked = linkage(tfidf_dense_transposed, 'ward')

plt.figure(figsize=(10, 20))
dendrogram(linked,
           orientation='top',
           distance_sort='descending',
           show_leaf_counts=True)
plt.title('Дендограмма иерархической кластеризации')
plt.xlabel('Индекс навыка')
plt.ylabel('Расстояние Уорда')
plt.show()

from scipy.cluster.hierarchy import fcluster

threshold_distance = 4.5
clusters = fcluster(linked, threshold_distance, criterion='distance')
clustered_skills_text = [[] for _ in range(max(clusters))]
for skill_index, cluster_id in enumerate(clusters):
    clustered_skills_text[cluster_id - 1].append(df_tfidf.columns[skill_index])

for i, skills in enumerate(clustered_skills_text, start=1):
    print(f"Кластер {i}: {skills}")

"""# 2. Моделька поиска кандидата на вакансию

## Получить текст резюме, очистить его
"""

#df = resumeDataSet['title'] + ' ' + resumeDataSet['city'] + ' ' + resumeDataSet['age'].astype(str) + ' лет ' + resumeDataSet['area'].astype(str) + ' ' + resumeDataSet['desired_wage'].astype(str) + ' ' + ' рублей ' + resumeDataSet['work_experience'].astype(str) + ' лет опыта ' + resumeDataSet['work_exp_descr'].astype(str) + ' ' + resumeDataSet['education_level'].astype(str) + ' ' + resumeDataSet['university'].astype(str) + ' ' + resumeDataSet['faculty'].astype(str) + ' ' + resumeDataSet['languages'].astype(str) + ' ' + resumeDataSet['skills'].astype(str)

#df = resumeDataSet['title'] + ' ' + resumeDataSet['city'] + ' ' + resumeDataSet['area'].astype(str) + ' ' + resumeDataSet['work_exp_descr'].astype(str) + ' ' + resumeDataSet['education_level'].astype(str) + ' ' + resumeDataSet['university'].astype(str) + ' ' + resumeDataSet['faculty'].astype(str) + ' ' + resumeDataSet['languages'].astype(str) + ' ' + resumeDataSet['skills'].astype(str)

df = resumeDataSet['work_exp_descr'].astype(str) + ' лет опыта ' + resumeDataSet['education_level'].astype(str) + ' ' + resumeDataSet['skills'].astype(str)

df = pd.DataFrame(df)
df.to_csv('exm.csv')

df = pd.read_csv('exm.csv')
df = df.iloc[:, 1:]
df.iloc[0]

df

import re
import pandas as pd
import spacy
from nltk.corpus import stopwords
import nltk
import pymorphy2
import inspect

# Инициализация анализатора pymorphy2
# morph = pymorphy2.MorphAnalyzer()

try:
    import pymorphy2
    morph = pymorphy2.MorphAnalyzer()
except Exception:
    # Заглушка если pymorphy2 не работает
    class DummyMorph:
        def parse(self, word):
            class ParseResult:
                def __init__(self, word):
                    self.normal_form = word.lower()
            return [ParseResult(word)]
    morph = DummyMorph()


russian_stopwords = stopwords.words('russian')

def cleanResume(resumeText):
    #resumeText = re.sub('http\S+\s*', ' ', resumeText)  # remove URLs
    #resumeText = re.sub('RT|cc', ' ', resumeText)  # remove RT and cc
    #resumeText = re.sub('#\S+', '', resumeText)  # remove hashtags
    #resumeText = re.sub('@\S+', '  ', resumeText)  # remove mentions
    resumeText = re.sub('[%s]' % re.escape("""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""), ' ', resumeText)  # remove punctuations
    #resumeText = re.sub(r'[^\x00-\x7f]',r' ', resumeText)
    resumeText = re.sub('\s+', ' ', resumeText)  # remove extra whitespace
    resumeText = re.sub('[\d]', ' ', resumeText)
    return resumeText

def process_text(text):
    # Токенизация текста
    words = text.split()

    # Список для хранения обработанных слов
    cleaned_text = []

    # Перебор слов в тексте
    for word in words:
        # Проверка слова на наличие в списке стоп-слов, исключение пунктуации и пробелов
        if word.lower() not in russian_stopwords: #and word.isalpha():
            # Получение леммы слова
            lemma = morph.parse(word)[0].normal_form
            cleaned_text.append(lemma)

    # Возврат обработанного текста в виде строки
    return " ".join(cleaned_text)

df['cleaned_resume'] = df['0'].apply(lambda x: cleanResume(x))
df['cleaned_resume'] = df['cleaned_resume'].apply(process_text)
df

df['cleaned_resume'] = df['cleaned_resume'].apply(lambda x: cleanResume(x))
df

df['cleaned_resume'][0]

df['cleaned_resume'][2]

"""## С помощью модели Bert векторизировать тексты резюме и вакансии"""

import pandas as pd
import torch
from transformers import BertTokenizer, BertModel

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

def get_bert_embeddings(text):
    # Encode the text using the tokenizer
    encoded_input = tokenizer(text, return_tensors='pt', max_length=512, truncation=True, padding='max_length')

    # Move encoded input to GPU if available
    if torch.cuda.is_available():
        encoded_input = {key: val.cuda() for key, val in encoded_input.items()}
        model.to('cuda')

    # Compute embeddings
    with torch.no_grad():
        outputs = model(**encoded_input)

    # Retrieve the embeddings for the [CLS] token (first token)
    embeddings = outputs.last_hidden_state[:, 0, :].squeeze()

    # Move embeddings back to CPU if on GPU
    if torch.cuda.is_available():
        embeddings = embeddings.cpu()

    return embeddings.numpy()  # Convert to numpy array

df['embeddings'] = df['cleaned_resume'][:100].apply(get_bert_embeddings)

import pandas as pd
import numpy as np
from numpy.linalg import norm

def cosine_similarity(v1, v2):
    return np.dot(v1, v2) / (norm(v1) * norm(v2))

query_vector = get_bert_embeddings(clean_vac)
# Применяем функцию и добавляем результат в датафрейм
df['similarity'] = df['embeddings'][:100].apply(lambda x: cosine_similarity(x, query_vector))

# Сортируем датафрейм по колонке сходства в порядке убывания
df_sorted = df.sort_values(by='similarity', ascending=False)

df_sorted[:30]

"""## Doc2Vec векторизация - обучение"""

!pip install gensim

import pandas as pd
import gensim
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt_tab')
nltk.download('punkt')


# Токенизация текстов в датафрейме
df['tagged_text'] = df['cleaned_resume'].apply(lambda x: TaggedDocument(words=word_tokenize(x.lower()), tags=[str(i)]))
tagged_data = df['tagged_text'].tolist()
# Инициализация модели Doc2Vec
model = Doc2Vec(vector_size=100, min_count=1, epochs=20)

# Построение словаря
model.build_vocab(tagged_data)

# Обучение модели
model.train(tagged_data, total_examples=model.corpus_count, epochs=model.epochs)

df['tokenized_text'] = df['cleaned_resume'].apply(lambda x: word_tokenize(x.lower()))
df['doc_vector'] = df['tokenized_text'].apply(lambda x: model.infer_vector(x))
df

vac = '''
Ты самостоятельный, у тебя есть опыт проектирования и ты можешь полностью взять на себя проектирование и реализацию блоков функционала;
Будет круто, если ты хочешь развиваться в менторинге и помогать младшим разработчикам.
Стек проектов

Python3, asyncio

aiohttp, fastApi в качестве основного фреймворка; Django чаще используем для админки

PostgresQL в качестве основной БД. Иногда используем MongoDB, но редко

Очереди на Redis, Tarantool, Kafka

Для деплоя kubernetes

Задачи

Проектирование и разработка новых фич и интеграций;
Небольшой процент поддержки и оптимизации кода;
Ревью кода других разработчиков команды;
Какой опыт важен

От 2 лет коммерческого опыта в релевантном стеке;
Опыт проектирования сервисов;
Опыт работы с асинхронным кодом;
Понимание алгоритмов и структур данных: считаем этот скилл важен особенно при проектировании, и решаем на собесах алгоритмические задачи;
'''
clean_vac = cleanResume(vac)
clean_vac = process_text(clean_vac)
clean_vac

import pandas as pd
import numpy as np
from numpy.linalg import norm

def cosine_similarity(v1, v2):
    return np.dot(v1, v2) / (norm(v1) * norm(v2))

query_vector = model.infer_vector(word_tokenize(clean_vac))
# Применяем функцию и добавляем результат в датафрейм
df['similarity'] = df['doc_vector'].apply(lambda x: cosine_similarity(x, query_vector))

# Сортируем датафрейм по колонке сходства в порядке убывания
df_sorted = df.sort_values(by='similarity', ascending=False)

df_sorted[:30]

"""## Tf-idf + модель схожести

Вакансия 1
"""

vac = '''
Ты самостоятельный, у тебя есть опыт проектирования и ты можешь полностью взять на себя проектирование и реализацию блоков функционала;
Будет круто, если ты хочешь развиваться в менторинге и помогать младшим разработчикам.
Стек проектов

Python3, asyncio

aiohttp, fastApi в качестве основного фреймворка; Django чаще используем для админки

PostgresQL в качестве основной БД. Иногда используем MongoDB, но редко

Очереди на Redis, Tarantool, Kafka

Для деплоя kubernetes

Задачи

Проектирование и разработка новых фич и интеграций;
Небольшой процент поддержки и оптимизации кода;
Ревью кода других разработчиков команды;
Какой опыт важен

От 2 лет коммерческого опыта в релевантном стеке;
Опыт проектирования сервисов;
Опыт работы с асинхронным кодом;
Понимание алгоритмов и структур данных: считаем этот скилл важен особенно при проектировании, и решаем на собесах алгоритмические задачи;
'''

"""Вакансия 2"""

vac = '''
Обязанности:
-Разработка и внедрение моделей NLP для различных областей.
-Разработка и внедрение кейсов использования LLM для различных областей.
-Разработка моделей компьютерного зрения для задач создания видео-контента.
-Оптимизация моделей машинного обучения для эффективного использования (например performance или real-time).
-Совместная работа с командой для внедрения моделей в технологический стек продуктов кампании.

Требования:
-Опыт работы с NLP или LLM моделями в реальных задачах.
-Опыт работы на реальных коммерческих проектах с области CV и ML/DL или NLP.
-Понимание основ компьютерного зрения, обработки изображений и работы с текстом.
-Опыт работы с TensorFlow, PyTorch, OpenCV и др.

Будет плюсом:
-Опыт работы с opensource LLM моделями локально.
-Опыт работы с нейронными сетями для анализа и обработки видео.'''

"""Вакансия 3"""

vac = '''
Обязанности:

Разработка архитектуры мобильного приложения с «нуля», участие во всех жизненных циклах развития приложения;
Проведение декомпозиции и оценки поставленных задач;
Тестирование и отладка реализованного функционала;
Участие в код ревью
Требования:

Опыт от 5 лет на аналогичной должности;
Опыт программирования на Kotlin;
Понимание жизненного цикла разработки ПО;
Понимание принципов проектирования SOLID, знание шаблонов проектирования, MVP MVI, MVVM и умение применять их на практике;
Умение писать поддерживаемый и тестируемый код, опыт написания unitтестов приветствуется;
Знание сетевых протоколов и технологий (HTTP(S), REST API, JSON);
Опыт многопоточного программирования, опыт работы с Coroutines;
Опыт работы с базами данных.
Будет плюсом, если ты:

Имеешь навыки проектирования и разработки архитектуры мобильных приложений
Способен протестировать свой код по заданной логике;
Любишь полностью погрузиться в бизнес-процесс и предлагать свое видение, а не просто выполнять задачи;
Имеешь опыт менторства других членов команды
'''

"""Вакансия 4"""

vac = '''
Вам предстоит:

Исследование и изучение данных;
Построение и поддержка ETL процессов (поиск данных, создание витрин данных и пр.);
Оптимизация расчетов;
Анализ логистических операций;
Создание витрин данных;
Оптимизация SQL запросов;
Улучшение BI отчетности внутри команды;
Участие в переходе аналитической отчетности на новые источники данных;
Взаимодействие с внутренними заказчиками и выявление потребностей бизнеса.
Мы ожидаем:

Высшее образование;
Опыт работы в роли аналитика данных от 2х лет;
Ответственность за результат;
Знание SQL, Python на продвинутом уровне;
Опыт построения витрин данных и регулярной отчетности;
Умение самостоятельно разбираться в чужом коде, а также в новых технологиях;
Опыт работы с BI-инструментами (Superset, Tableau, Power BI), опыт работы с СУБД Vertica, Microsoft SQL, Clickhouse;
Опыт работы с Airflow, Kafka будет плюсом.'''

"""Вакансия 5"""

vac = '''
Задачи, над которыми нужно будет работать:

Поддерживать, развивать и мониторить существующие Kubernetes-кластера.
Улучшать и развивать существующий CI/CD процесс на базе GitOps (ArgoCD, Gitlab, Jira).
Автоматизировать развертывание приложений (мы используем Helm, ansible).
Дорабатывать существующее Blockchain-as-a-Service решение на базе облачных технологий.
Участвовать в проведении технических работ на площадках заказчиков.
Самостоятельно искать новые возможности для улучшения инфраструктуры и внедрения новых DevOps практик.
Ждем от кандидата:
Опыт разработки CI/CD пайплайнов с использованием GitLab.
Опыт работы с Docker и Kubernetes.
Понимание основ сетевых технологий (семейство TCP/IP).
Опыт администрирования linux-инфраструктуры.
Опыт работы в команде.
Будет плюсом - опыт работы с GitOps.
Будет плюсом - опыт работы с технологией blockchain.
Большой плюс - знание языков программирования Python, Golang.'''

"""## Построение самой модели"""

df = resumeDataSet['work_exp_descr'].astype(str) + ' лет опыта ' + resumeDataSet['education_level'].astype(str) + ' ' + resumeDataSet['skills'].astype(str)

df = pd.DataFrame(df)
df.to_csv('exm.csv')

df = pd.read_csv('exm.csv')
df = df.iloc[:, 1:]

import re
import pandas as pd
import spacy
from nltk.corpus import stopwords
import nltk
import pymorphy2
import inspect

# Инициализация анализатора pymorphy2
# morph = pymorphy2.MorphAnalyzer()

try:
    import pymorphy2
    morph = pymorphy2.MorphAnalyzer()
except Exception:
    # Заглушка если pymorphy2 не работает
    class DummyMorph:
        def parse(self, word):
            class ParseResult:
                def __init__(self, word):
                    self.normal_form = word.lower()
            return [ParseResult(word)]
    morph = DummyMorph()

russian_stopwords = stopwords.words('russian')

def cleanResume(resumeText):
    #resumeText = re.sub('http\S+\s*', ' ', resumeText)  # remove URLs
    #resumeText = re.sub('RT|cc', ' ', resumeText)  # remove RT and cc
    #resumeText = re.sub('#\S+', '', resumeText)  # remove hashtags
    #resumeText = re.sub('@\S+', '  ', resumeText)  # remove mentions
    resumeText = re.sub('[%s]' % re.escape("""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""), ' ', resumeText)  # remove punctuations
    #resumeText = re.sub(r'[^\x00-\x7f]',r' ', resumeText)
    resumeText = re.sub('\s+', ' ', resumeText)  # remove extra whitespace
    resumeText = re.sub('[\d]', ' ', resumeText)
    return resumeText

def process_text(text):
    # Токенизация текста
    words = text.split()

    # Список для хранения обработанных слов
    cleaned_text = []

    # Перебор слов в тексте
    for word in words:
        # Проверка слова на наличие в списке стоп-слов, исключение пунктуации и пробелов
        if word.lower() not in russian_stopwords: #and word.isalpha():
            # Получение леммы слова
            lemma = morph.parse(word)[0].normal_form
            cleaned_text.append(lemma)

    # Возврат обработанного текста в виде строки
    return " ".join(cleaned_text)

df['cleaned_resume'] = df['0'].apply(lambda x: cleanResume(x))
df['cleaned_resume'] = df['cleaned_resume'].apply(process_text)
df['cleaned_resume'] = df['cleaned_resume'].apply(lambda x: cleanResume(x))
df

print(df.iloc[2, 0])

print(df.iloc[2, 1])

clean_vac = cleanResume(vac)
clean_vac = process_text(clean_vac)
clean_vac

new_row = pd.DataFrame({'0': [clean_vac],'cleaned_resume': [clean_vac]})
df = pd.concat([df, new_row], ignore_index=True)
df

# df = df.loc[[74, 76, 77, 83, 84, 85, 89, 155, 226, 257, 1013, 1058, 93, 248, 274, 2384], :]

# df = df.loc[[1538, 1376, 243, 135, 1042, 1043, 1044, 1057, 1442, 1453, 1459, 1471, 74, 76, 77, 83, 84, 85, 89, 155, 226, 257, 1013, 1058, 93, 248, 274], :]



df

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')

tfidf_matrix = tfidf.fit_transform(df['cleaned_resume'])

dense_tfidf_matrix = tfidf_matrix.todense()

# Преобразование матрицы в DataFrame для наглядности
tfidf_df = pd.DataFrame(dense_tfidf_matrix, columns=tfidf.get_feature_names_out())
tfidf_df

from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# Допустим, мы ищем резюме, наиболее похожие на первое (индекс 0)
similar_indices = cosine_sim[2384].argsort()  # Исключаем само резюме, сортируем по возрастанию

# Вывод топ-5 наиболее похожих резюме
print("Резюме наиболее похожие на первое резюме:")
df_new1 = df.iloc[similar_indices[::-1]]
df_new1 ['cosine_sim'] = pd.DataFrame(cosine_sim[2384])
df_new1[1:11]

df_new1.iloc[1, 0]

"""Для 12 резюме"""

from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# Допустим, мы ищем резюме, наиболее похожие на первое (индекс 0)
similar_indices = cosine_sim[27].argsort()  # Исключаем само резюме, сортируем по возрастанию

# Вывод топ-5 наиболее похожих резюме
print("Резюме наиболее похожие на первое резюме:")
df_new1 = df.iloc[similar_indices[::-1]]
df_new1.index = (list(range(0, 28)))
df_new1 ['cosine_sim'] = pd.DataFrame(sorted(cosine_sim[27])[::-1])
df_new1[1:28]

similar_indices[::-1]

cosine_sim[15]

df_new1.to_excel('pri1.xlsx')

# Функция для создания и отображения облаков слов в виде матрицы 2x3 без заголовков
def plot_common_words_matrix_2x3(tfidf_matrix, feature_names, doc_index, rows=2, cols=3):
    fig, axes = plt.subplots(rows, cols, figsize=(18, 8))  # Новый размер под матрицу 2x3
    axes = axes.flatten()

    for i in range(1, 7):  # Отображение только для первых шести документов
        # Получение ненулевых значений TF-IDF для обоих документов
        doc_words = tfidf_matrix.iloc[0, :].to_numpy().nonzero()[0]
        compare_words = tfidf_matrix.iloc[i, :].to_numpy().nonzero()[0]

        # Поиск общих слов (пересечение)
        common_words_idx = list(set(doc_words) & set(compare_words))

        # Словарь слов и их TF-IDF значений для облака слов
        common_words_scores = {feature_names[idx]: tfidf_matrix.iloc[i, idx] for idx in common_words_idx}

        # Создание облака слов
        wordcloud = WordCloud(width=400, height=400, background_color='white')
        wordcloud.generate_from_frequencies(common_words_scores)

        axes[i-1].imshow(wordcloud, interpolation='bilinear')
        axes[i-1].axis('off')  # Скрываем оси

    # Убираем лишние слоты, если они есть
    for j in range(i, len(axes)):
        fig.delaxes(axes[j])

    plt.tight_layout()
    plt.show()

# Визуализация облаков слов для документа 1 со первыми шестью документами в виде матрицы 2x3
plot_common_words_matrix_2x3(new_data, new_data.columns, 0)

df['cleaned_resume'][1538]

resumeDataSet['title'][902]

df['cleaned_resume'][2098]

